project:
  type: website

render:
  - "index.qmd"
  - "schedule.qmd"
  - "homework.qmd"
  - "supplementary.qmd"
  - "license.qmd"

website:
  site-url: https://stat153.berkeley.edu/fall-2024/
  google-analytics: G-ZLC7WVGHGY
          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



